services:
  db:
    image: mysql:5.7.38
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3315:3306
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    build:
      context: ./docker/wordpress
    ports:
      - 8081:80
    restart: always
    env_file:
      - ./docker/xdebug/.env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wp:/var/www/html
volumes:
  db_data:
